version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: ./support/dev/Dockerfile
    working_dir: /work
    command: ./support/dev/run
    volumes:
      - .:/work
      - stack-global:/root/.stack

  ci:
    image: docker.pkg.github.com/alistairb/label-maker/label-maker-ci-base
    working_dir: /work
    volumes:
      - .:/work

volumes:
  stack-global:
    external: true
