version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: ./support/dev/Dockerfile
    working_dir: /work
    command: ./support/dev/run
    volumes:
      - .:/work
      - stack-global:/root/.stack

  ci:
    # waiting on https://github.com/elgohr/Publish-Docker-Github-Action/issues/52
    image: docker.pkg.github.com/alistairb/label-maker/label-maker-ci-base:ee09d63eee1c9434037dbd6c2ee6b6ffcacd1220
    working_dir: /work
    volumes:
      - .:/work

volumes:
  stack-global:
    external: true
