name:                label-maker
version:             0.1.0.0
github:              "alistairb/label-maker"
license:             BSD3
author:              "Alistair B"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/label-maker#readme>

dependencies:
- base >= 4.12 && < 5

library:
  source-dirs: src
  ghc-options:
  # Recommended settings for polysemy
  - -O2
  - -flate-specialise
  - -fspecialise-aggressively
  - -fplugin=Polysemy.Plugin
  dependencies:
  - polysemy
  - polysemy-plugin
  - yaml
  - aeson
  - vector
  - github
  - parallel-io
  - unordered-containers
  - text

ghc-options:
  # Useful warnings
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wcompat
  - -Widentities
  - -Wredundant-constraints
  - -fhide-source-paths
  - -Wmissing-export-lists
  - -Wpartial-fields


default-extensions:
  - DataKinds
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - OverloadedStrings
  - StrictData
  - MultiWayIf

executables:
  label-maker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - label-maker
    - optparse-applicative

    # dev dependencies
    - hlint
    - weeder

tests:
  label-maker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - label-maker
    - raw-strings-qq
    - yaml
    - bytestring
