#!/bin/bash
set -Eexuo pipefail

cd $(dirname $0)/..

GITHUB_ACTIONS=${GITHUB_ACTIONS-false}

if [ "$GITHUB_ACTIONS" = true ];
then
    SERVICE=ci
else
    SERVICE=dev
fi

# Create volume
docker volume create --name stack-global > /dev/null

mkdir -p ./dist

docker-compose build $SERVICE

# Run dev script or use what is passed in as arguments
docker-compose run --rm $SERVICE "$@"
