organizations:
  scala-course:
    repos: all

labels:
  sync:
    zomg-duplicate:
      color: '000000'
    invalid:
      color: '333333'
    new-label:
      color: 'b98fe0'
  delete:
    - bug
  rename:
    - old-label-name: duplicate
      new-label-name: zomg-duplicate

  # ####### Project Initiatives #######
  # ">agency-profile-publisher" => "67e5d0", # cyan
  # ">ad-components-lift-shift" => "67e5d0", # cyan
  # ">cp-jobs-to-cloud" => "67e5d0", # cyan
  # ">ignite-lpapi-filters" => "67e5d0", # cyan
  # ">impersonation" => "67e5d0", # cyan
  # ">jetstream" => "67e5d0", # cyan
  # ">listings-exports" => "67e5d0", # cyan
  # ">locations-15" => "67e5d0", # cyan
  # ">locations-16" => "67e5d0", # cyan
  # ">lp-data-analyst" => "67e5d0", # cyan
  # ">myfun-lp" => "67e5d0", # cyan
  # ">pseeker-migration-uplift" => "67e5d0", # cyan
  # ">quote-and-buy" => "67e5d0", # cyan
  # ">reaxml-uplift" => "67e5d0", # cyan
  # ">resi-profile-publish" => "67e5d0", # cyan
  # ">soft-suspend" => "67e5d0", # cyan
  # "milestone1" => "b98fe0", # light purple
  # "milestone2" => "b98fe0", # light purple
  # "milestone3" => "b98fe0", # light purple
  # "milestone4" => "b98fe0", # light purple
  # "milestone5" => "b98fe0", # light purple
  # "milestone6" => "b98fe0", # light purple
  # "okr/custodianship" => "027051", # deep green
  # "okr/customer-service" => "027051", # deep green
  # "okr/smart-switchoff" => "027051", # deep green
  # ####### Card Scoring #######
  # ")must-have" => "cbe537",
  # ")nice-to-have" => "cbe537",
  # ")should-have" => "cbe537",
  # "value/1-low" => "ede080", # mustard
  # "value/2-medium" => "ede080", # mustard
  # "value/3-high" => "ede080", # mustard
  # "value/4-highest" => "ede080", # mustard
  # "cost/1-x-large" => "76ef6b", # lime
  # "cost/2-large" => "76ef6b", # lime
  # "cost/3-medium" => "76ef6b", # lime
  # "cost/4-small" => "76ef6b", # lime
  # ####### Other Labels #######
  # "blocked" => "a726e2",
  # "bq-ingester-blocker" => "0e8a16", # dark green
  # "bug" => "d73a4a",
  # "design" => "c6ea77", # yellow green
  # "do-not-merge" => "ed5cd9", # pink
  # "duplicate" => "cccccc",
  # "epic" => "e99695", # light red
  # "haz-free-friday" => "000000", # black
  # "high-risk" => "d93f0b",
  # "kicked-off" => "0052cc", # blue
  # "not-committed" => "ef9d70", # orange
  # "outlier" => "000000", # black
  # "pending-information" => "f2ffb2",
  # "PIR-action" => "0052cc", # deep blue
  # "qa-fail" => "e5c385", # light brown
  # "qa-task" => "fcdbbd", # light orange
  # "ready-for-prod" => "5319e7", # purple blue
  # "recurring-issue" => "c2c6f9", # very light purple
  # "spike" => "64fc94", # light green
  # "tech-debt" => "120a8f", # ultramarine
  # "wip" => "f9c2ca" # light pink
