organizations:
  scala-course:
    repos: all
  locations:
    repos:
      - atlas
      - atlas-java-sdk


labels:
  sync:
    zomg-duplicate: '000000'
    invalid: '333333'
    new-label: b98fe0
  delete:
    - bug
  rename:
    - old-label-name: duplicate
      new-label-name: zomg-duplicate
