name: Publish CI Base Image

on:
  push:
    paths:
    - 'stack.yaml.lock'
    - 'support/ci-base/**'
    branches:
      - master

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Publish CI Base Image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: alistairb/label-maker/label-maker-ci-base
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        dockerfile: support/ci-base/Dockerfile
        workdir: .
        tag_names: true
