name: Publish CI Base Image

on:
  pull_request:
    paths:
    - 'stack.yaml'
    - 'stack.yaml.lock'
    - 'package.yaml'
    - 'custom-snapshot.yaml'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Publish CI Base Image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: AlistairB/label-maker/label-maker-ci-base
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
        dockerfile: support/ci-base/Dockerfile
        context: .
