name: Verify

on:
  - push
  - pull_request

jobs:

  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      name: docker login
      with:
        login-server: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Tests
      run: auto/test
    - name: HLint
      run: auto/hlint
    - name: GHC Warning Check
      run: auto/ghc-check
    - name: Weeder
      run: auto/weeder
