name: Verify

on: [push, pull_request]

jobs:

  hlint:
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: docker.pkg.github.com
      SERVICE: ci

    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      name: docker login
      with:
        login-server: ${{ DOCKER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Tests
      run: auto/test
    - name: HLint
      run: auto/hlint
    - name: GHC Warning Check
      run: auto/ghc-check
    - name: Weeder
      run: auto/weeder
