name: Verify

on: [push, pull_request]

jobs:

  hlint:
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: docker.pkg.github.com

    steps:
    - uses: actions/checkout@v1
    - name: docker login
      run: echo "$GITHUB_TOKEN" | docker login -u AlistairB --password-stdin "$DOCKER_REGISTRY"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: HLint
      env:
        SERVICE: ci
      run: auto/hlint
    - name: GHC Warning Check
      env:
        SERVICE: ci
      run: auto/ghc-check
