name: Verify

on: pull_request

jobs:

  hlint:
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: docker.pkg.github.com
      SERVICE: ci

    steps:
    - uses: actions/checkout@v1
    - name: docker login
      run: echo "$GITHUB_TOKEN" | docker login -u AlistairB --password-stdin "$DOCKER_REGISTRY"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Tests
      run: auto/test
    - name: HLint
      run: auto/hlint
    - name: GHC Warning Check
      run: auto/ghc-check
    - name: Weeder
      run: auto/weeder
